<script setup lang="ts">
definePageMeta({ middleware:'auth' })
const empty=()=>({name:'',unit:'กก.',quantity:0,minimumQuantity:0,currentPrice:0})
const form=reactive(empty());const message=ref('');const editingId=ref('')
const {data:items,refresh}=await useFetch<any[]>('/api/ingredients',{default:()=>[]})
async function create(){message.value='';try{await $fetch('/api/ingredients',{method:'POST',body:form});Object.assign(form,empty());await refresh()}catch(e:any){message.value=e?.data?.statusMessage||'บันทึกไม่สำเร็จ'}}
async function update(item:any){await $fetch(`/api/ingredients/${item.id}`,{method:'PATCH',body:{name:item.name,unit:item.unit,quantity:Number(item.quantity),minimumQuantity:Number(item.minimumQuantity),currentPrice:Number(item.currentPrice)}});editingId.value='';await refresh()}
</script>
<template><div><AppNav/><main class="admin-page"><div class="page-title"><div><p class="eyebrow">Inventory</p><h1>วัตถุดิบ</h1></div></div><form class="panel form-row" @submit.prevent="create"><label>ชื่อ<input v-model="form.name" required></label><label>หน่วย<input v-model="form.unit" required></label><label>คงเหลือ<input v-model.number="form.quantity" type="number" min="0" step="any"></label><label>จุดเตือน<input v-model.number="form.minimumQuantity" type="number" min="0" step="any"></label><label>ราคาต่อหน่วย<input v-model.number="form.currentPrice" type="number" min="0" step="any"></label><button class="right-submit">เพิ่มวัตถุดิบ</button><p v-if="message" class="error">{{message}}</p></form><div class="panel table-wrap"><table><thead><tr><th>วัตถุดิบ</th><th>หน่วย</th><th>คงเหลือ</th><th>จุดเตือน</th><th>ราคา</th><th>สถานะ</th><th></th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td><input v-if="editingId===item.id" v-model="item.name"><strong v-else>{{item.name}}</strong></td><td><input v-if="editingId===item.id" v-model="item.unit" class="small-input"><span v-else>{{item.unit}}</span></td><td><input v-if="editingId===item.id" v-model.number="item.quantity" type="number" min="0" step="any" class="small-input"><span v-else>{{item.quantity}}</span></td><td><input v-if="editingId===item.id" v-model.number="item.minimumQuantity" type="number" min="0" step="any" class="small-input"><span v-else>{{item.minimumQuantity}}</span></td><td><input v-if="editingId===item.id" v-model.number="item.currentPrice" type="number" min="0" step="any" class="small-input"><span v-else>{{item.currentPrice}} ฿</span></td><td><span :class="Number(item.quantity)<=Number(item.minimumQuantity)?'low':''">{{Number(item.quantity)<=Number(item.minimumQuantity)?'ใกล้หมด':'ปกติ'}}</span></td><td><button v-if="editingId!==item.id" class="secondary" @click="editingId=item.id">แก้ไข</button><button v-else @click="update(item)">บันทึก</button></td></tr></tbody></table></div></main></div></template>
