<script setup lang="ts">
definePageMeta({middleware:'auth'})
type Role='cashier'|'kitchen'|'manager'|'admin'
const empty=()=>({username:'',name:'',password:'',role:'cashier' as Role,imageUrl:null as string|null})
const form=reactive(empty());const message=ref('');const editingId=ref('');const uploading=ref('')
const {data:staff,refresh}=await useFetch<any[]>('/api/staff',{default:()=>[]})
async function uploadImage(file:File){const body=new FormData();body.append('image',file);return await $fetch<{url:string}>('/api/uploads/image',{method:'POST',body})}
async function chooseImage(event:Event,target:any,key:string){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;uploading.value=key;try{const result=await uploadImage(file);target.imageUrl=result.url;if(key!=='new')await update(target)}finally{uploading.value=''}}
async function save(){message.value='';try{await $fetch('/api/staff',{method:'POST',body:form});Object.assign(form,empty());await refresh()}catch(e:any){message.value=e?.data?.statusMessage||'บันทึกไม่สำเร็จ'}}
async function update(row:any){const body:any={username:row.username,name:row.name,role:row.role,imageUrl:row.imageUrl,active:row.active};if(row.newPassword)body.password=row.newPassword;await $fetch(`/api/staff/${row.id}`,{method:'PATCH',body});row.newPassword='';editingId.value='';await refresh()}
async function toggle(row:any){row.active=!row.active;await update(row)}
</script>
<template><div><AppNav/><main class="admin-page"><div class="page-title"><div><p class="eyebrow">Access control</p><h1>บัญชีพนักงานและแอดมิน</h1></div></div>
<form class="panel form-row" @submit.prevent="save"><label>รูปภาพ<input type="file" accept="image/*" @change="chooseImage($event,form,'new')"></label><img v-if="form.imageUrl" :src="form.imageUrl" class="avatar"><label>Username<input v-model="form.username" required></label><label>ชื่อ<input v-model="form.name" required></label><label>รหัสผ่าน<input v-model="form.password" type="password" minlength="8" required></label><label>สิทธิ์<select v-model="form.role"><option value="cashier">แคชเชียร์</option><option value="kitchen">ครัว</option><option value="manager">ผู้จัดการ</option><option value="admin">แอดมิน</option></select></label><button class="right-submit" :disabled="uploading==='new'">เพิ่มพนักงาน</button><p v-if="message" class="error">{{message}}</p></form>
<div class="panel table-wrap"><table><thead><tr><th>รูป</th><th>ชื่อ</th><th>Username</th><th>สิทธิ์</th><th>รหัสผ่านใหม่</th><th>สถานะ</th><th></th></tr></thead><tbody><tr v-for="row in staff" :key="row.id"><td><label class="avatar-picker"><img v-if="row.imageUrl" :src="row.imageUrl" class="avatar"><span v-else class="avatar placeholder">👤</span><input type="file" accept="image/*" @change="chooseImage($event,row,row.id)"></label></td><td><input v-if="editingId===row.id" v-model="row.name"><strong v-else>{{row.name}}</strong></td><td><input v-if="editingId===row.id" v-model="row.username"><span v-else>{{row.username}}</span></td><td><select v-if="editingId===row.id" v-model="row.role"><option value="cashier">แคชเชียร์</option><option value="kitchen">ครัว</option><option value="manager">ผู้จัดการ</option><option value="admin">แอดมิน</option></select><span v-else>{{row.role}}</span></td><td><input v-if="editingId===row.id" v-model="row.newPassword" type="password" minlength="8" placeholder="เว้นไว้ถ้าไม่เปลี่ยน"><span v-else>••••••••</span></td><td>{{row.active?'ใช้งาน':'ปิด'}}</td><td><button v-if="editingId!==row.id" class="secondary" @click="editingId=row.id">แก้ไข</button><button v-else @click="update(row)">บันทึก</button> <button class="secondary" @click="toggle(row)">{{row.active?'ปิด':'เปิด'}}</button></td></tr></tbody></table></div>
</main></div></template>
